<?php

namespace Database\Seeders;

use App\Models\Icd10;
use Illuminate\Database\Seeder;

/**
 * Kode ICD-10 yang paling sering dipakai di layanan rawat jalan.
 * Bukan daftar lengkap ICD-10 — cukup untuk dipakai dokter sehari-hari
 * dan bisa ditambah lewat master data.
 */
class Icd10Seeder extends Seeder
{
    private const KODE = [
        ['A01.0', 'Demam tifoid'],
        ['A06.0', 'Disentri amuba akut'],
        ['A09', 'Diare dan gastroenteritis diduga infeksi'],
        ['A15.0', 'Tuberkulosis paru dengan konfirmasi bakteriologis'],
        ['A90', 'Demam dengue'],
        ['A91', 'Demam berdarah dengue'],
        ['B00.9', 'Infeksi virus herpes simpleks'],
        ['B01.9', 'Varisela tanpa komplikasi'],
        ['B02.9', 'Herpes zoster tanpa komplikasi'],
        ['B05.9', 'Campak tanpa komplikasi'],
        ['B15.9', 'Hepatitis A tanpa koma hepatik'],
        ['B16.9', 'Hepatitis B akut tanpa koma hepatik'],
        ['B18.1', 'Hepatitis B kronik'],
        ['B35.3', 'Tinea pedis'],
        ['B35.4', 'Tinea korporis'],
        ['B35.6', 'Tinea kruris'],
        ['B36.0', 'Pitiriasis versikolor'],
        ['B37.9', 'Kandidiasis'],
        ['B54', 'Malaria tanpa keterangan'],
        ['B77.9', 'Askariasis'],
        ['B86', 'Skabies'],
        ['D50.9', 'Anemia defisiensi besi'],
        ['D64.9', 'Anemia tanpa keterangan'],
        ['E03.9', 'Hipotiroidisme'],
        ['E05.9', 'Tirotoksikosis (hipertiroid)'],
        ['E10.9', 'Diabetes melitus tipe 1 tanpa komplikasi'],
        ['E11.9', 'Diabetes melitus tipe 2 tanpa komplikasi'],
        ['E44.0', 'Malnutrisi energi protein sedang'],
        ['E66.9', 'Obesitas'],
        ['E78.5', 'Hiperlipidemia'],
        ['F32.9', 'Episode depresi'],
        ['F41.1', 'Gangguan cemas menyeluruh'],
        ['F51.0', 'Insomnia non-organik'],
        ['G43.9', 'Migrain'],
        ['G44.2', 'Nyeri kepala tipe tegang'],
        ['H00.0', 'Hordeolum'],
        ['H01.0', 'Blefaritis'],
        ['H10.9', 'Konjungtivitis'],
        ['H11.0', 'Pterigium'],
        ['H16.9', 'Keratitis'],
        ['H25.9', 'Katarak senilis'],
        ['H52.1', 'Miopia'],
        ['H52.4', 'Presbiopia'],
        ['H60.9', 'Otitis eksterna'],
        ['H61.2', 'Serumen obturans'],
        ['H65.9', 'Otitis media non-supuratif'],
        ['H66.9', 'Otitis media supuratif'],
        ['I10', 'Hipertensi esensial (primer)'],
        ['I20.9', 'Angina pektoris'],
        ['I25.9', 'Penyakit jantung iskemik kronik'],
        ['I50.9', 'Gagal jantung'],
        ['I83.9', 'Varises vena tungkai bawah'],
        ['J00', 'Nasofaringitis akut (common cold)'],
        ['J01.9', 'Sinusitis akut'],
        ['J02.9', 'Faringitis akut'],
        ['J03.9', 'Tonsilitis akut'],
        ['J04.0', 'Laringitis akut'],
        ['J06.9', 'Infeksi saluran napas atas akut (ISPA)'],
        ['J11.1', 'Influenza dengan manifestasi pernapasan'],
        ['J18.9', 'Pneumonia'],
        ['J20.9', 'Bronkitis akut'],
        ['J30.4', 'Rinitis alergi'],
        ['J31.0', 'Rinitis kronis'],
        ['J35.0', 'Tonsilitis kronis'],
        ['J44.9', 'Penyakit paru obstruktif kronik (PPOK)'],
        ['J45.9', 'Asma'],
        ['K02.9', 'Karies gigi'],
        ['K04.7', 'Abses periapikal'],
        ['K05.1', 'Gingivitis kronis'],
        ['K08.1', 'Kehilangan gigi karena pencabutan'],
        ['K12.0', 'Stomatitis aftosa rekuren'],
        ['K21.0', 'Refluks gastroesofageal dengan esofagitis'],
        ['K29.7', 'Gastritis'],
        ['K30', 'Dispepsia'],
        ['K59.0', 'Konstipasi'],
        ['K60.2', 'Fisura ani'],
        ['K64.9', 'Hemoroid'],
        ['K76.0', 'Perlemakan hati'],
        ['L01.0', 'Impetigo'],
        ['L02.9', 'Abses kulit, furunkel, dan karbunkel'],
        ['L03.9', 'Selulitis'],
        ['L08.9', 'Infeksi lokal kulit dan jaringan bawah kulit'],
        ['L20.9', 'Dermatitis atopik'],
        ['L23.9', 'Dermatitis kontak alergi'],
        ['L29.9', 'Pruritus'],
        ['L30.9', 'Dermatitis'],
        ['L40.9', 'Psoriasis'],
        ['L50.9', 'Urtikaria'],
        ['L70.0', 'Akne vulgaris'],
        ['M06.9', 'Artritis reumatoid'],
        ['M10.9', 'Gout'],
        ['M15.9', 'Poliartrosis'],
        ['M17.9', 'Osteoartritis lutut (gonartrosis)'],
        ['M54.2', 'Servikalgia'],
        ['M54.3', 'Skiatika'],
        ['M54.5', 'Nyeri punggung bawah'],
        ['M75.0', 'Kapsulitis adhesif bahu'],
        ['M79.1', 'Mialgia'],
        ['N18.9', 'Penyakit ginjal kronik'],
        ['N20.0', 'Batu ginjal'],
        ['N30.0', 'Sistitis akut'],
        ['N39.0', 'Infeksi saluran kemih'],
        ['N40', 'Hiperplasia prostat'],
        ['N76.0', 'Vaginitis akut'],
        ['N91.2', 'Amenorea'],
        ['N94.6', 'Dismenorea'],
        ['O21.0', 'Hiperemesis gravidarum ringan'],
        ['O26.9', 'Kondisi terkait kehamilan'],
        ['O80', 'Persalinan spontan tunggal'],
        ['P59.9', 'Ikterus neonatal'],
        ['R05', 'Batuk'],
        ['R10.4', 'Nyeri perut'],
        ['R11', 'Mual dan muntah'],
        ['R42', 'Pusing berputar (vertigo)'],
        ['R50.9', 'Demam tanpa sebab yang diketahui'],
        ['R51', 'Nyeri kepala'],
        ['R53', 'Malaise dan kelelahan'],
        ['R63.4', 'Penurunan berat badan abnormal'],
        ['S61.9', 'Luka terbuka pergelangan tangan dan tangan'],
        ['T14.1', 'Luka terbuka pada regio badan tidak spesifik'],
        ['T78.4', 'Alergi tanpa keterangan'],
        ['Z00.0', 'Pemeriksaan kesehatan umum'],
        ['Z23', 'Imunisasi'],
        ['Z30.9', 'Kontrasepsi'],
        ['Z34.9', 'Pengawasan kehamilan normal'],
        ['Z76.0', 'Permintaan resep ulang'],
        ['A03.9', 'Shigellosis'],
        ['A04.9', 'Infeksi usus bakterial lain'],
        ['A08.4', 'Infeksi usus karena virus'],
        ['A16.2', 'Tuberkulosis paru tanpa konfirmasi bakteriologis'],
        ['A38', 'Skarlatina'],
        ['A46', 'Erisipelas'],
        ['A49.9', 'Infeksi bakteri tanpa keterangan'],
        ['B24', 'Penyakit HIV'],
        ['B30.9', 'Konjungtivitis karena virus'],
        ['B34.9', 'Infeksi virus tanpa keterangan'],
        ['B82.9', 'Parasitisme usus'],
        ['D17.9', 'Lipoma'],
        ['D22.9', 'Nevus melanositik'],
        ['D23.9', 'Neoplasma jinak kulit'],
        ['D25.9', 'Mioma uteri'],
        ['E14.9', 'Diabetes melitus tidak spesifik'],
        ['E16.2', 'Hipoglikemia'],
        ['E86', 'Dehidrasi (deplesi volume)'],
        ['E87.6', 'Hipokalemia'],
        ['F20.9', 'Skizofrenia'],
        ['F43.2', 'Gangguan penyesuaian'],
        ['G40.9', 'Epilepsi'],
        ['G51.0', 'Bell palsy'],
        ['G56.0', 'Sindrom terowongan karpal'],
        ['G62.9', 'Polineuropati'],
        ['H57.1', 'Nyeri mata'],
        ['H81.0', 'Penyakit Meniere'],
        ['H81.1', 'Vertigo posisional paroksismal benigna'],
        ['H92.0', 'Otalgia (nyeri telinga)'],
        ['H93.1', 'Tinitus'],
        ['I63.9', 'Infark serebral (stroke iskemik)'],
        ['I64', 'Stroke tidak spesifik'],
        ['I67.9', 'Penyakit serebrovaskular'],
        ['I73.9', 'Penyakit vaskular perifer'],
        ['I95.9', 'Hipotensi'],
        ['J22', 'Infeksi saluran napas bawah akut'],
        ['J32.9', 'Sinusitis kronis'],
        ['J40', 'Bronkitis'],
        ['J42', 'Bronkitis kronis'],
        ['J43.9', 'Emfisema'],
        ['J47', 'Bronkiektasis'],
        ['J90', 'Efusi pleura'],
        ['K01.1', 'Gigi impaksi'],
        ['K03.6', 'Deposit pada gigi (karang gigi)'],
        ['K05.3', 'Periodontitis kronis'],
        ['K13.7', 'Lesi mukosa mulut'],
        ['K25.9', 'Ulkus lambung'],
        ['K27.9', 'Ulkus peptikum'],
        ['K35.8', 'Apendisitis akut'],
        ['K40.9', 'Hernia inguinalis'],
        ['K42.9', 'Hernia umbilikalis'],
        ['K52.9', 'Gastroenteritis dan kolitis non-infeksi'],
        ['K58.9', 'Sindrom iritasi usus'],
        ['K80.2', 'Batu kandung empedu'],
        ['K92.2', 'Perdarahan saluran cerna'],
        ['L21.9', 'Dermatitis seboroik'],
        ['L27.0', 'Erupsi obat generalisata'],
        ['L60.0', 'Kuku tumbuh ke dalam'],
        ['L72.1', 'Kista ateroma'],
        ['L84', 'Klavus dan kalus'],
        ['L98.9', 'Gangguan kulit tanpa keterangan'],
        ['M13.9', 'Artritis'],
        ['M19.9', 'Artrosis'],
        ['M25.5', 'Nyeri sendi'],
        ['M47.9', 'Spondilosis'],
        ['M51.2', 'Pergeseran diskus intervertebralis'],
        ['M62.6', 'Ketegangan otot'],
        ['M65.9', 'Sinovitis dan tenosinovitis'],
        ['M77.1', 'Epikondilitis lateral'],
        ['M81.9', 'Osteoporosis'],
        ['N10', 'Pielonefritis akut'],
        ['N23', 'Kolik ginjal'],
        ['N43.3', 'Hidrokel'],
        ['N45.9', 'Orkitis dan epididimitis'],
        ['N61', 'Mastitis'],
        ['N63', 'Benjolan payudara'],
        ['N70.9', 'Salpingitis dan ooforitis'],
        ['N72', 'Servisitis'],
        ['N73.9', 'Penyakit radang panggul'],
        ['N75.1', 'Kista Bartholin'],
        ['N83.2', 'Kista ovarium'],
        ['N92.0', 'Menstruasi berlebihan dan teratur'],
        ['N93.9', 'Perdarahan uterus abnormal'],
        ['N95.1', 'Keadaan menopause'],
        ['O00.9', 'Kehamilan ektopik'],
        ['O03.9', 'Abortus spontan'],
        ['O13', 'Hipertensi gestasional'],
        ['O14.9', 'Preeklampsia'],
        ['O23.4', 'Infeksi saluran kemih pada kehamilan'],
        ['R00.0', 'Takikardia'],
        ['R03.0', 'Tekanan darah tinggi tanpa diagnosis hipertensi'],
        ['R06.0', 'Sesak napas (dispnea)'],
        ['R07.4', 'Nyeri dada'],
        ['R14', 'Kembung dan flatulensi'],
        ['R21', 'Ruam kulit'],
        ['R22.9', 'Benjolan lokal'],
        ['R30.0', 'Disuria'],
        ['R31', 'Hematuria'],
        ['R32', 'Inkontinensia urin'],
        ['R35', 'Poliuria'],
        ['R55', 'Sinkop dan kolaps'],
        ['R56.0', 'Kejang demam'],
        ['R60.0', 'Edema lokal'],
        ['R73.9', 'Hiperglikemia'],
        ['S00.9', 'Cedera superfisial kepala'],
        ['S01.0', 'Luka terbuka kulit kepala'],
        ['S30.9', 'Cedera superfisial abdomen dan panggul'],
        ['S40.9', 'Cedera superfisial bahu dan lengan atas'],
        ['S50.9', 'Cedera superfisial lengan bawah'],
        ['S70.9', 'Cedera superfisial pinggul dan paha'],
        ['S80.9', 'Cedera superfisial tungkai bawah'],
        ['S90.9', 'Cedera superfisial pergelangan kaki dan kaki'],
        ['S93.4', 'Keseleo pergelangan kaki'],
        ['T30.0', 'Luka bakar'],
        ['T63.4', 'Efek toksik sengatan serangga'],
        ['T78.2', 'Syok anafilaktik'],
        ['T78.3', 'Angioedema'],
        ['Z01.0', 'Pemeriksaan mata'],
        ['Z03.9', 'Observasi atas dugaan penyakit'],
        ['Z09.9', 'Pemeriksaan tindak lanjut'],
        ['Z11.1', 'Skrining tuberkulosis'],
        ['Z13.1', 'Skrining diabetes melitus'],
        ['Z32.0', 'Kehamilan belum terkonfirmasi'],
        ['Z35.9', 'Pengawasan kehamilan risiko tinggi'],
        ['Z39.2', 'Perawatan pascapersalinan rutin'],
        ['Z48.0', 'Perawatan balutan dan jahitan'],
        ['Z71.3', 'Konsultasi dan pengawasan diet'],
    ];

    public function run(): void
    {
        foreach (self::KODE as [$kode, $nama]) {
            Icd10::updateOrCreate(['kode' => $kode], ['nama_id' => $nama]);
        }
    }
}
